# This file is part of Astarte.
#
# Copyright 2025 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Elixir CI

on:
  push:
    branches:
      - main
      - "release-*"
  pull_request:
    branches:
      - "**"

env:
  elixir_version: "1.15.7"
  otp_version: "26.1"

permissions:
  contents: read

jobs:
  test-dialyzer:
    name: Check Dialyzer
    runs-on: ubuntu-22.04
    env:
      MIX_ENV: ci
    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1.16.0
        with:
          elixir-version: ${{ env.elixir_version }}
          otp-version: ${{ env.otp_version }}
      - uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-mix-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-mix-
      - name: Install Dependencies
        run: mix deps.get
      - name: Run dialyzer
        run: mix dialyzer
      - name: Run credo
        run: mix credo --strict

  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    needs: test-dialyzer
    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1.16.0
        with:
          elixir-version: ${{ env.elixir_version }}
          otp-version: ${{ env.otp_version }}
      - uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-mix-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-mix-
      - name: Install Dependencies
        run: mix deps.get
      - name: Run Tests
        run: mix test
