# This file is part of Astarte.
#
# Copyright 2025 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Elixir CI

on:
  push:
    branches:
      - main
      - "release-*"
  pull_request:

permissions:
  contents: read

jobs:
  gate:
    name: Block when forbidden label is present
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Skip on non-PR events
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "Not a pull_request event; gate passes."

      - name: Fail if 'You shall not pass!' label is present
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const BLOCK = 'You shall not pass!';
            const labels = (context.payload.pull_request.labels || []).map(l => l.name.toLowerCase());
            if (labels.includes(BLOCK.toLowerCase())) {
              core.setFailed(`Blocked by label '${BLOCK}'. Remove it to merge.`);
            } else {
              core.info('OK: blocking label not present.');
            }

  setup:
    name: Setup
    runs-on: ubuntu-22.04
    needs: gate
    env:
      MIX_ENV: ci
    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1.18.0
        id: setup-elixir
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: actions/cache@v4
        id: cache-deps
        with:
          path: deps
          key: ${{ runner.os }}-${{ steps.setup-elixir.outputs.elixir-version }}-${{ steps.setup-elixir.outputs.otp-version }}-mix-${{ hashFiles('mix.lock') }}
      - name: Install Dependencies and Compile
        run: mix deps.get && mix deps.compile
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: _build

  dializer:
    name: Run Dialyzer
    runs-on: ubuntu-22.04
    needs: [gate, setup]
    env:
      MIX_ENV: ci
    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1.18.0
        id: setup-elixir
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: actions/cache@v4
        id: cache-deps
        with:
          path: deps
          key: ${{ runner.os }}-${{ steps.setup-elixir.outputs.elixir-version }}-${{ steps.setup-elixir.outputs.otp-version }}-mix-${{ hashFiles('mix.lock') }}
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Run Dialyzer
        run: mix dialyzer
      - name: Run credo
        run: mix credo

  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    needs: [gate, setup]
    env:
      MIX_ENV: ci
    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1.18.0
        id: setup-elixir
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-${{ steps.setup-elixir.outputs.elixir-version }}-${{ steps.setup-elixir.outputs.otp-version }}-mix-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.setup-elixir.outputs.elixir-version }}-${{ steps.setup-elixir.outputs.otp-version }}-mix-
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Run Unit Tests & Coverage
        run: mix test --cover
